version: "3.8"

services:
  quiz-bot:
    build: .
    container_name: neuroquiz-bot
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./Montserrat-Regular.ttf:/app/Montserrat-Regular.ttf
      - ./Montserrat-Black.ttf:/app/Montserrat-Black.ttf
      - ./logo.jpg:/app/logo.jpg
      - ./assets:/app/assets
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
